//
// Created by dima on 1/16/20.
//

#ifndef SEARCHING_ALGORITHMS_SERVER__FILECACHEMANAGER_H_
#define SEARCHING_ALGORITHMS_SERVER__FILECACHEMANAGER_H_

class FileCacheManager {

};

#endif //SEARCHING_ALGORITHMS_SERVER__FILECACHEMANAGER_H_
